#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.8
# from Racc grammer file "".
#

require 'racc/parser.rb'

require 'blast_furnace/lexer'
require 'blast_furnace/nodes'
module BlastFurnace
  class Parser < Racc::Parser

module_eval(<<'...end grammar.y/module_eval...', 'grammar.y', 21)
  def parse(code, show_tokens=false)
    @lexer = BlastFurnace::Lexer.new code
    do_parse # Kickoff the parsing process
  end

  def next_token
    @lexer.next
  end
...end grammar.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
     3,     4,     5,     6 ]

racc_action_check = [
     0,     1,     3,     4 ]

racc_action_pointer = [
    -2,     1,   nil,    -1,     3,   nil,   nil ]

racc_action_default = [
    -1,    -4,    -2,    -4,    -4,    -3,     7 ]

racc_goto_table = [
     1,     2 ]

racc_goto_check = [
     1,     2 ]

racc_goto_pointer = [
   nil,     0,     1 ]

racc_goto_default = [
   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  0, 5, :_reduce_1,
  1, 5, :_reduce_2,
  2, 6, :_reduce_3 ]

racc_reduce_n = 4

racc_shift_n = 7

racc_token_table = {
  false => 0,
  :error => 1,
  :class => 2,
  :identifier => 3 }

racc_nt_base = 4

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "class",
  "identifier",
  "$start",
  "Root",
  "Expression" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'grammar.y', 7)
  def _reduce_1(val, _values, result)
     result = [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 8)
  def _reduce_2(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 12)
  def _reduce_3(val, _values, result)
     result = [:class, val[1]] 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module BlastFurnace
